### ISSUE TITLE
Merge to upstream

### ISSUE THREAD

**Issue by CodeDoctorDE** [CapeCrusader321/linwood-butterfly-snap#2]
Hello,
I saw your project recommended on github.
I'm the official developer of butterfly and it would be nice if you can merge it upstream to make it an official snap on snapcraft.
Feel free to create a pull request and add these files in the `app/linux/snap` directory.

Initially I wanted to add it but on my computer, the build always failed on fedora.

**Comment by CodeDoctorDE** [comment]
And `linwood` is the name of the org where I organize all my projects.
It would be useful to name repo `linwood-butterfly-snap` or `butterfly-snap`.
I have other apps published, for example `linwood-flow`

**Comment by CapeCrusader321** [comment]
@CodeDoctorDE  That really nice, i will be opening a pr soon in the mainstream repos soon.

**Comment by CapeCrusader321** [comment]
@CodeDoctorDE  Some questions once i merge this upstream, who will be publishing this snap, the upstream account or from my account ??

**Comment by CodeDoctorDE** [comment]
I would post it under my account and link to you

**Comment by CapeCrusader321** [comment]
> I would post it under my account and link to you

Ok, you can simply add me as a collaborator, we will discuss this later, first let me prepare the pr

**Comment by CapeCrusader321** [comment]
@CodeDoctorDE  Done, created a pr

**Comment by CodeDoctorDE** [comment]
I already registered the snapcraft.io/Butterfly listing. I saw you could deploy it automatically on a new version

**Comment by CapeCrusader321** [comment]
> I already registered the snapcraft.io/Butterfly listing. I saw you could deploy it automatically on a new version

Can you be more clear please, am not sure if i understood you ?

**Comment by CodeDoctorDE** [comment]
![Screenshot 2023-05-05 at 10-22-51 Listing details for butterfly](https://user-images.githubusercontent.com/20452814/236410189-e2acd534-d58f-4afb-9c08-9a33ca7d3ba8.png)
That's the app I created there.
Linwood isn't the name of the app, it's the org where all my projects are hosted.
Will the version property be changed on every release?

**Comment by CapeCrusader321** [comment]
Closing this as this is completed and shifted to --> https://github.com/LinwoodDev/Butterfly/pull/376
